apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-postgresql-data" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
    component: postgresql
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storage.postgresql.storageClass }}
  storageClassName: {{ .Values.global.storage.postgresql.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.global.storage.postgresql.size }}
