apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db-secret" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  db-secret: {{ required "global.db.password is required. Set it with --set global.db.password=<value>" .Values.global.db.password | quote }}
  pgpassword: {{ .Values.global.db.password | quote }}
