apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-postgresql-headless" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.global.db.port }}
      targetPort: {{ .Values.global.db.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-postgresql" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
    component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.global.db.port }}
      targetPort: {{ .Values.global.db.port }}
      protocol: TCP
