apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-grafana-secret" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
