apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-node-exporter" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.commonLabels" . | nindent 4 }}
    component: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ printf "%s-node-exporter" .Release.Name }}
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
