apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-pg-exporter" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.commonLabels" . | nindent 4 }}
    component: pg-exporter
spec:
  type: ClusterIP
  selector:
    app: {{ printf "%s-pg-exporter" .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.postgresqlExporter.port }}
      targetPort: 9187
      protocol: TCP
