apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-prometheus-data" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storage.prometheus.storageClass }}
  storageClassName: {{ .Values.global.storage.prometheus.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.global.storage.prometheus.size }}
