apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-rosetta-api-config" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosetta-api.commonLabels" . | nindent 4 }}
data:
  NETWORK: {{ .Values.global.network | quote }}
  API_SPRING_PROFILES_ACTIVE: "online"
