apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rosetta-api" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosetta-api.commonLabels" . | nindent 4 }}
    component: rosetta-api
spec:
  type: ClusterIP
  selector:
    {{- include "rosetta-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
---
{{- if .Values.service.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-rosetta-api-external" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosetta-api.commonLabels" . | nindent 4 }}
    component: rosetta-api
spec:
  type: {{ .Values.service.external.type | default "LoadBalancer" }}
  selector:
    {{- include "rosetta-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
{{- end }}
