apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ include "cardano-rosetta-java.namespace" . }}
  labels:
    {{- include "cardano-rosetta-java.commonLabels" . | nindent 4 }}
