name: "integration-test"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set up environment"
        run: docker compose --env-file .env.IntegrationTest -f docker-integration-test-environment.yaml up --build -d --wait
      - name: "Wait for node to be populated"
        run: "sleep 30s"
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'
      - name: "Update Genesis block number"
        run: |
          source ./.env.IntegrationTest
          echo "$UPDATE_GENESIS_BLOCK_QUERY" > temp.sql
          PGPASSWORD=$DB_SECRET psql -h localhost -p 5432 -d $DB_NAME -U $DB_USER -f temp.sql
      - name: "Install newman"
        run: npm install -g newman
#      - name: "Install mesh-cli"
#        run: curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/master/scripts/install.sh | sh -s

      # https://github.com/coinbase/mesh-cli/issues/422
      - name: "Install mesh-cli"
        run: curl -sSfL https://raw.githubusercontent.com/coinbase/mesh-cli/v0.10.3/scripts/install.sh | sed -e 's/^REPO=.*/REPO=mesh-cli/' | sh -s

      - name: "Run tests"
        run: newman run ./postmanTests/rosetta-java.postman_collection.json -e postmanTests/Rosetta-java-env.postman_environment.json -r cli
      - name: "Run rosetta check:data tests"
        run: ./bin/rosetta-cli check:data --configuration-file ./rosetta-cli-tests/data/byron_sample.json
      - name: "Tear down environment"
        run: docker compose --env-file .env.IntegrationTest -f docker-integration-test-environment.yaml down
